--==================--
--Magnitude Analysis--
--==================--

--Finding total customers by countries
SELECT 
	country,
	count(customer_number) AS total_customers
FROM Gold.dim_customers
GROUP BY country
ORDER BY country;


--Finding total customers by gender
SELECT 
	gender,
	count(gender) AS total_customers
FROM Gold.dim_customers
GROUP BY gender
ORDER BY gender;


--Finding total products by category
SELECT
	categorry,
	COUNT(product_name) total_products
FROM Gold.dim_product
GROUP BY categorry
ORDER BY categorry;


--what is average costs in each category?
SELECT
	categorry,
	AVG(cost) AS average_cost
FROM Gold.dim_product
GROUP BY categorry
ORDER BY categorry;


--what is the total revenue generated for each category?
SELECT 
	dp.categorry,
	SUM(fs.sales_amount) As sum_of_revenue
FROM
	Gold.dim_product dp
LEFT JOIN Gold.fact_sales fs
ON dp.product_key=fs.product_key
GROUP BY dp.categorry
ORDER BY dp.categorry;


--Finding total revenue is generated by each customer
SELECT 
	dc.first_name,
	SUM(fs.sales_amount) As sum_of_revenue
FROM
	Gold.dim_customers dc
LEFT JOIN Gold.fact_sales fs
ON dc.customer_key=fs.customer_key
GROUP BY dc.first_name
ORDER BY dc.first_name;
 

--what is the distribution of sold items accross countries?
SELECT
DC.country,
SUM(fs.quantity) AS sold_items
FROM Gold.fact_sales fs
LEFT JOIN Gold.dim_customers dc
ON fs.customer_key=dc.customer_key
GROUP BY dc.country
ORDER BY dc.country